# Generated by Django 4.1 on 2022-11-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='gif',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
