# Generated by Django 4.1 on 2022-09-17 03:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='showing',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='film',
            field=models.TextField(default='Missing Film Name', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='showing',
            name='time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='showing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seats_taken', serialize=False, to='ticketapp.showing'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tcolumn',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='trow',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('showing', 'trow', 'tcolumn')},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
    ]
