# Generated by Django 4.1 on 2022-11-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='film',
        ),
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default='No comment', max_length=500),
        ),
    ]
