# Generated by Django 4.1 on 2022-12-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_remove_review_film_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
