# Generated by Django 4.1 on 2022-12-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_ticket_expired'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'movie')},
        ),
    ]
