# Generated by Django 4.1 on 2022-12-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0006_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
