# Generated by Django 4.1 on 2023-01-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_siteuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
