# Generated by Django 4.1 on 2023-01-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_siteuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
